### ISSUE TITLE
Youtube playlist download issue 

### ISSUE THREAD

**Issue by Lucifer-00007** [stefnotch/downline#11]
When i am trying to download a playlist for each video of the playlist i have to click the download button!

**Comment by Lucifer-00007** [comment]
> When i am trying to download a playlist for each video of the playlist i have to click the download button!

I have found this but I have new issue now:
- After giving a custom download path the videos are getting downloaded in the default path
- When i download a video a thumbnail is also downloading and there is no option to avoid it!

**Comment by stefnotch** [comment]
@Lucifer-00007 I'll take a look at those issues in the upcoming weeks

**Comment by Janldeboer** [comment]
> * After giving a custom download path the videos are getting downloaded in the default path

This was fixed by https://github.com/stefnotch/downline/commit/968f97e0a9450b6efe4ea8083f2fa3e6486acb46

**Comment by Janldeboer** [comment]
> When i am trying to download a playlist for each video of the playlist i have to click the download button!

All videos can be downloaded at once, by opening the bottom menu (arrow in the bottom centre to open it) and then clicking the play button
