### ISSUE TITLE
macOS builds aren't working

### ISSUE THREAD

**Issue by Janldeboer** [stefnotch/downline#27]
The newly created builds for macOS aren't working.
While `cargo tauri dev` build a fully functional program,
`cargo tauri build` builds an app that is executable, but not functional.
By using `cargo tauri build --debug` and the page inspector, we figured out that the following exception was raised:
```
Unhandled Promise Rejection: No such file or directory (os error 2)
```

**Comment by stefnotch** [comment]
Should be fixed

**Comment by stefnotch** [comment]
See also https://github.com/tauri-apps/tauri/issues/4788
