### ISSUE TITLE
No Mac Download

### ISSUE THREAD

**Issue by EAGBCD** [stefnotch/downline#6]
Hello. 

Many times on this and other pages related it says this is a software for Mac as well. But I can only find a download for windows. 

Is there a Mac download somewhere?

Thank you.

**Comment by stefnotch** [comment]
It should be possible to compile this software for MacOS and Linux. (see https://github.com/stefnotch/downline#build-instructions ) 

However, I have neither of those things at hand, nor have I set up GitHub actions for it. This means that I don't provide binaries at the moment.

Also relevant:
https://tauri.app/v1/guides/building/debian
https://tauri.app/v1/guides/building/macos

**Comment by EAGBCD** [comment]
Thank you. 

I'm not much of a coder so I may need a bit of help. 

I download Tauri for Mac and then download your source files here. Then I run Tauri and run the commands in your build instructions? How do I get Tauri to see your files though?

Or have I got it all wrong?

Thanks again.

**Comment by stefnotch** [comment]
Ideally you should be able to go to where you downloaded my source files, and then run the commands there

Here is a Windows screenshot, with the file browser on the left side, and the terminal on the right side. Notice how the path is exactly where the files are. Hopefully it's similar enough on MacOS.

![image](https://user-images.githubusercontent.com/10220080/196003155-fd870302-0649-412d-8c25-f4e9bd42ab8d.png)

**Comment by EAGBCD** [comment]
Thanks. 

I finally go it after getting the prerequisites and also nodejs I was able to run your commands.

Well not really... 

It just gets stuck at 

Bundling downline.app

And makes my computer fans go crazy. But there is no app or anything. Not really sure at all what to do, there are no instructions past this.

Thanks.

**Comment by stefnotch** [comment]
I see, that's a real shame. Well, I guess the easiest solution for you would be to find another youtube-dl GUI that works on MacOS
https://www.reddit.com/r/youtubedl/wiki/info-guis/

I don't think I'll be able to get a Mac in the foreseeable future.

**Comment by EAGBCD** [comment]
Is it meant to launch the app after the  'Bundling downline.app' stage?

I've been looking theres only a few Mac ones, and all don't work for me unfortunately.

Surprising and frustrating how difficult it is to download youtube video as mp3 in good quality is. 

Thanks for trying to help, appreciate it.

**Comment by stefnotch** [comment]
Yes it should, at least after a while

**Comment by Janldeboer** [comment]
Building should now work properly, there is also a Mac version provided for download, but we're unsure if it's fully functional yet.

**Comment by Janldeboer** [comment]
They don't work yet. I made new issue for the underlying problem.
https://github.com/stefnotch/downline/issues/27
